language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - git remote set-url git@github.com/chemgymrl/chemgymrl
  - pip install mkdocs
  - mkdocs build
  - mkdocs gh-deploy
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: site
  target_branch: gh-pages
  on:
    repo: chemgymrl/chemgymrl
    branches:
      only: 
        - main 