language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - pip install mkdocs
  - mkdocs build
  - mkdocs gh-deploy
deploy:
  provider: pages
  skip_cleanup: true
  GITHUB_TOKEN: $0c1e9986e839ff47a77a8874031286f9033c38b5
  keep_history: true
  local_dir: site
  target_branch: gh-pages
  on:
    repo: chemgymrl/chemgymrl
    branches:
      only: 
        - main